# Generated by Django 6.0.1 on 2026-01-30 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Building', models.CharField(max_length=100)),
                ('Capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=100)),
                ('Course', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('Specialization', models.CharField(choices=[('it_web', 'Веб-разработка'), ('auto_industrial', 'Промышленная автоматизация'), ('auto_robotics', 'Робототехника'), ('economy_banking', 'Банковское дело'), ('design_graphic', 'Графический дизайн'), ('design_interior', 'Дизайн интерьера')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('NumOfHours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classrooms')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('TokenNum', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('GradeType', models.CharField(choices=[('test', 'Зачет'), ('exam', 'Экзамен'), ('currrent_control', 'Текущий контроль')], max_length=30)),
                ('Mark', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть меньше 0'), django.core.validators.MaxValueValidator(100, message='Значение не может быть больше 100')])),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('attended', 'Присутствовал'), ('absent', 'Отсутствовал'), ('valid_reason', 'Уважительная причина')], max_length=30)),
                ('Date', models.DateField()),
                ('Schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teachers'),
        ),
    ]
