# Generated by Django 6.0.1 on 2026-02-05 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Reason',
            field=models.TextField(blank=True, verbose_name='Причина отсутствия'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
