# Generated by Django 6.0.1 on 2026-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendance_created_at_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
