# Generated by Django 6.0.1 on 2026-02-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_students_user_teachers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.groups'),
        ),
    ]
